export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const VACATION_LOADING = 'VACATION_LOADING';
export const GET_VACATIONS = 'GET_VACATIONS';
export const GET_VACATION = 'GET_VACATION';
export const ADD_VACATION = 'ADD_VACATION';
export const DELETE_VACATION = 'DELETE_VACATION';
